language: ruby

# cache: bundler
# We would like to enable travis' bundler cache (cache: bundler) but for some reason
# travis installs our bundle under the test directory (test/vendor/bundle/*) and, as a
# result, travis tries to run all of the tests of all of our dependencies!
# TODO: There's probably a way to configure the bundle path

before_install:
  - gem update --system
  - gem update bundler

rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3

gemfile:
  - test/gemfiles/Gemfile.rails-4.2.x
  - test/gemfiles/Gemfile.rails-5.0.x
  - test/gemfiles/Gemfile.rails-5.1.x
  - test/gemfiles/Gemfile.rails-master

matrix:
  allow_failures:
    - gemfile: test/gemfiles/Gemfile.rails-master
  exclude:
    - rvm: 2.1.10
      gemfile: test/gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.1.10
      gemfile: test/gemfiles/Gemfile.rails-5.1.x
  fast_finish: true

sudo: false
